### CREATE LABECLASS
POST http://localhost:3003/class
Content-Type: application/json

{
    "name": "Lamarr"
}

### CREATE STUDENT
POST http://localhost:3003/student
Content-Type: application/json

{
    "name": "João",
    "email": "joao@email.com",
    "birth_date": "05/04/1993",
    "class_id": "1673381034100",
    "hobbies": ["Viajar", "Correr", "Surfar"]
}

### CREATE TEACHER
POST http://localhost:3003/teacher
Content-Type: application/json

{
    "name": "Carlos",
    "email": "carlos@email.com",
    "birth_date": "28/09/1981",
    "class_id": "1673389942500",
    "specialties": ["JS", "React"]
}

### CHANGE MODULE
PUT http://localhost:3003/classes/1673389942500
Content-Type: application/json

{
   "newModule": "4"
}

### CHANGE STUDENT CLASS
PUT http://localhost:3003/students/1673382814953
Content-Type: application/json

{
   "newClassId": "1673389942500"
}

### CHANGE TEACHER CLASS
PUT http://localhost:3003/teachers/1673393713688
Content-Type: application/json

{
   "newClassId": "1673389942500"
}


### GET ACTIVE CLASSES
GET http://localhost:3003/classes

### GET STUDENT
GET http://localhost:3003/student?name=regina

### GET TEACHERS
GET http://localhost:3003/teachers